# Generated by Django 4.0.2 on 2022-03-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(default=0, max_length=20)),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=20, unique=True)),
                ('email', models.CharField(default=None, max_length=100)),
                ('password1', models.CharField(max_length=20, unique=True)),
                ('password2', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
